# Generated by Django 4.2 on 2023-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertemp',
            name='step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
