# Generated by Django 4.2 on 2023-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank',
            field=models.CharField(default=1, max_length=512, verbose_name='Юридическое лицо банк'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='inn',
            field=models.CharField(default=1, max_length=512, verbose_name='СТИР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='legal_entity_address',
            field=models.CharField(default=1, max_length=512, verbose_name='Адрес юридического лица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='legal_entity_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Наименования юридического лица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='mfo',
            field=models.CharField(default=1, max_length=512, verbose_name='МФО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name_shef',
            field=models.CharField(default=1, max_length=512, verbose_name='Контактное лицо(Ф.И.О)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='schot',
            field=models.CharField(default=1, max_length=512, verbose_name='Р/С'),
            preserve_default=False,
        ),
    ]
