# Generated by Django 4.2 on 2023-05-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code verified'), ('half_done', 'Done without MyID'), ('done', 'Done')], default='new', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code verified'), ('half_done', 'Done without MyID'), ('done', 'Done')], default='new', max_length=60),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='SimpleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(max_length=9, verbose_name='Номер паспорта')),
                ('pinfl', models.CharField(blank=True, error_messages={'unique': 'A user with that pinfl already exists.'}, max_length=14, null=True, unique=True, verbose_name='ПИНФЛ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационной номер налогоплательщика')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пол')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обычные пользователи',
                'verbose_name_plural': 'Обычные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя продавца')),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя Менеджер')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
