# Generated by Django 4.2 on 2023-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendor_account_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleusers',
            name='pinfl',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that pinfl already exists.'}, max_length=100, null=True, unique=True, verbose_name='ПИНФЛ'),
        ),
    ]
