# Generated by Django 4.2 on 2024-02-09 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_seller_district_alter_seller_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
