# Generated by Django 4.2 on 2023-05-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicaluser_auth_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='simpleusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.manager'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='seller',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.seller'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='simple_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.simpleusers'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.vendor'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to='users.manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to='users.seller'),
        ),
        migrations.AddField(
            model_name='user',
            name='simple_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to='users.simpleusers'),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to='users.vendor'),
        ),
    ]
