# Generated by Django 4.2 on 2023-08-28 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=512, verbose_name='Модел')),
                ('imei1', models.CharField(max_length=100, verbose_name='IMEI 1')),
                ('sku', models.CharField(max_length=512, verbose_name='SKU')),
            ],
        ),
        migrations.CreateModel(
            name='Cashbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('types', models.IntegerField(choices=[(1, 'Начисление Кэшбэка'), (2, 'Cписание Кэшбэка')])),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата Добавлена')),
                ('model', models.CharField(max_length=512, verbose_name='Модел')),
                ('imei1', models.CharField(max_length=100, unique=True, verbose_name='IMEI 1')),
                ('sku', models.CharField(max_length=512, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=512)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('budget', models.IntegerField()),
                ('status', models.CharField(choices=[('wait', 'Ожидает одобрения модератором CashBek'), ('active', 'Активный'), ('refused', 'Отклоненный'), ('pause', 'Пауза'), ('finish', 'Завершенный')], default='wait', max_length=10)),
                ('description', models.CharField(default='', max_length=1024)),
                ('who', models.CharField(default='', max_length=1024)),
                ('price_procent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.UUIDField(default=uuid.uuid4)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=100, null=True)),
                ('chat_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempPriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TempPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('budget', models.IntegerField()),
                ('products', models.ManyToManyField(related_name='temp_promo', to='main.products')),
            ],
        ),
    ]
