# Generated by Django 4.2 on 2023-06-13 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendor_account_vendor'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='GSM', max_length=512, verbose_name='Категория')),
                ('model', models.CharField(max_length=512, verbose_name='Модел')),
                ('sku', models.CharField(max_length=512, verbose_name='SKU')),
                ('imei1', models.CharField(max_length=100, unique=True, verbose_name='IMEI 1')),
                ('imei2', models.CharField(default='', max_length=100, verbose_name='IMEI 2')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата Добавлена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor_account'),
        ),
    ]
