# Generated by Django 4.2 on 2023-09-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbek',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_product', to='main.products'),
        ),
        migrations.AlterField(
            model_name='cashbek',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_promo', to='main.promo'),
        ),
        migrations.AlterField(
            model_name='cashbek',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_seller', to='users.seller'),
        ),
        migrations.AlterField(
            model_name='cashbek',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_user', to='users.simpleusers'),
        ),
        migrations.AlterField(
            model_name='cashbek',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_vendor', to='users.vendor'),
        ),
    ]
