# Generated by Django 4.2 on 2023-09-04 06:54

import apps.main.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=256)),
                ('question_ru', models.CharField(max_length=256)),
                ('answer_uz', models.CharField(max_length=2400)),
                ('answer_ru', models.CharField(max_length=2400)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_uz', models.CharField(max_length=256)),
                ('title_ru', models.CharField(max_length=256)),
                ('body_uz', models.TextField(max_length=1000)),
                ('body_ru', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
            ],
        ),
        migrations.AddField(
            model_name='cashbek',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cashbek',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashbek',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.promo'),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='all_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr_code',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr_code',
            name='types',
            field=models.IntegerField(choices=[(1, 'Начисление Кэшбэка'), (2, 'Cписание Кэшбэка')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Token_confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.main.utility.get_random_token, max_length=16)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('types', models.IntegerField(choices=[(1, 'Начисление Кэшбэка'), (2, 'Cписание Кэшбэка')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.simpleusers')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ReadNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='main.notifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.simpleusers')),
            ],
        ),
        migrations.CreateModel(
            name='Fribase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_id', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.simpleusers')),
            ],
        ),
    ]
