# Generated by Django 4.2 on 2023-06-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendor_account_vendor'),
        ('main', '0003_remove_products_status_alter_blacklistproducts_imei1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blacklistproducts',
            name='imei2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imei2',
        ),
        migrations.AddField(
            model_name='blacklistproducts',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.vendor_account'),
            preserve_default=False,
        ),
    ]
