# Generated by Django 4.2 on 2023-10-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_seller_district_alter_seller_region'),
        ('main', '0003_alter_cashbek_product_alter_cashbek_promo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOfVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('descriptions', models.CharField(default='', max_length=1024)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_vendor', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('descriptions', models.CharField(default='', max_length=1024)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_seller', to='users.seller')),
            ],
        ),
    ]
