# Generated by Django 4.2 on 2023-09-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0003_faq_notifications_cashbek_description_cashbek_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbek',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.simpleusers'),
        ),
    ]
