# Generated by Django 4.2 on 2023-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cashbek_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbek',
            name='user_phone',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
