# Generated by Django 4.2 on 2023-07-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='budget',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='products',
            field=models.ManyToManyField(related_name='promo', to='main.products'),
        ),
        migrations.AddField(
            model_name='promo',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('active', 'active'), ('finish', 'finish')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TempPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('budget', models.IntegerField()),
                ('products', models.ManyToManyField(related_name='temp_promo', to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='TempPriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temppromo')),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promo')),
            ],
        ),
    ]
