# Generated by Django 4.2 on 2023-07-05 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_promo_budget_promo_products_promo_status_temppromo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='price_procent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
