# Generated by Django 4.2 on 2023-07-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_price'),
        ('main', '0008_temppromo_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.vendor_account'),
            preserve_default=False,
        ),
    ]
