# Generated by Django 4.2 on 2023-07-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_promo_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temppromo',
            name='vendor',
        ),
    ]
