# Generated by Django 4.2 on 2023-07-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_price'),
        ('main', '0010_remove_temppromo_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppromo',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.vendor_account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('active', 'active'), ('refused', 'refused'), ('finish', 'finish')], max_length=10),
        ),
    ]
