# Generated by Django 4.2 on 2023-08-21 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_promo_who_alter_promo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.UUIDField(default=uuid.UUID('fd0015e0-1add-45e4-a8e2-030da16a99ac'))),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2023, 8, 21, 14, 14, 58, 46905))),
                ('is_used', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
