# Generated by Django 4.2 on 2023-08-21 10:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_qr_code_chat_id_alter_qr_code_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='chat_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 15, 9, 51, 958417)),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='message_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='qr_id',
            field=models.UUIDField(default=uuid.UUID('a2d2336a-3a43-41b6-8e1b-2a93c5187471')),
        ),
    ]
