# Generated by Django 4.2 on 2023-08-23 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_price'),
        ('main', '0017_alter_qr_code_expiry_date_alter_qr_code_qr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='qr_id',
            field=models.UUIDField(default=uuid.UUID('2904062a-a44a-495e-8592-5d1c840fa15b')),
        ),
        migrations.CreateModel(
            name='IncomeCashbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.simpleusers')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCashbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.simpleusers')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
