# Generated by Django 4.2 on 2023-08-24 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_qr_code_qr_id_incomecashbek_expensecashbek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='qr_id',
            field=models.UUIDField(default=uuid.UUID('5714774e-089c-4a1e-a174-1858a4b71def')),
        ),
    ]
