# Generated by Django 4.2 on 2023-08-24 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_qr_code_qr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='qr_id',
            field=models.UUIDField(default=uuid.UUID('7f540dc0-5b86-4dcf-92e5-d5bfe36511ca')),
        ),
    ]
